AWSTemplateFormatVersion: "2010-09-09"
Description: Test CloudFormation Deployment

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/24
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Stack
          Value: Test
        - Key: Name
          Value: CF-Test-VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 172.16.0.0/28
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Stack
          Value: Test
        - Key: Name
          Value: CF-Public-Subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 172.16.0.16/28
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Stack
          Value: Test
        - Key: Name
          Value: CF-Public-Subnet-2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Stack
          Value: Test
        - Key: Name
          Value: CF-Public-Route-Table

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Stack
          Value: Test
        - Key: Name
          Value: CF-Internet-Gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref InternetGateway


